name: check
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v4
      - id: sccache
        uses: mozilla-actions/sccache-action@v0.0.7
      - id: deps
        uses: ./.github/
      - id: check
        run: >
          just check ${{ steps.deps.outputs.clang-version }}
          '-pr ./profiles/clang'
          '-o "&:clang_tidy_executable=clang-tidy-${{ steps.deps.outputs.clang-version }}"'
          '-o "&:compiler_launcher=sccache"'
