name: lint
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: mmalenic/evlist@main
      - run: pre-commit run --all-files
      - run: gcc --version
      - run: cmake --version
