name: publish
on:
  release:
    types: [published]

jobs:
  ci:
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
      - id: checkout
        uses: actions/checkout@v4
      - id: sccache
        uses: mozilla-actions/sccache-action@v0.0.7
      - id: deps
        uses: mmalenic/evlist@main
      - id: package
        run: >
          export VERSION=${{ github.ref_name }} &&
          just package Release evlist-${VERSION#v}.$(uname -m)_linux.tar.gz ''
          '-o "&:compiler_launcher=sccache"'
      - id: publish
        uses: softprops/action-gh-release@v2
        with:
          files: build/Release/evlist-*.tar.gz*
