on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - id: release
        env:
          GH_TOKEN: ${{ secrets.EVLIST_TOKEN }}
        uses: googleapis/release-please-action@v4
