name: test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [{ c: clang, cpp: clang++ }, { c: gcc, cpp: g++ }]
    steps:
      - uses: actions/checkout@v4
      - id: dependencies
        uses: mmalenic/evlist@main
      - id: test
        run: >
          just memcheck Release
          -o build_testing=True
          -s compiler=${{ matrix.compiler.c }}
          -s compiler.version=${{ steps.dependencies.outputs[format('{0}-version', matrix.compiler.c)] }}
          -pr ./.github/workflows/conan_profile
        env:
          C_EXECUTABLE: ${{ matrix.compiler.c }}-${{ steps.dependencies.outputs[format('{0}-version', matrix.compiler.c)] }}
          CPP_EXECUTABLE: ${{ matrix.compiler.cpp }}-${{ steps.dependencies.outputs[format('{0}-version', matrix.compiler.c)] }}
          CXX_FLAGS: ${{ matrix.compiler.c == 'clang' && '["-fsanitize=address,undefined,leak,integer", "-Wall", "-Wextra", "-Wpedantic", "-Werror"]' || '' }}
