name: test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    strategy:
      matrix:
        compiler: [clang, gcc]
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v4
      - id: sccache
        uses: mozilla-actions/sccache-action@v0.0.7
      - id: deps
        uses: ./.github/
      - id: args
        run: >
          echo "args=-InputDeviceLister* ${{ steps.deps.outputs[format('{0}-version', matrix.compiler)] }}
          '-o \"&:compiler_launcher=sccache\"'" >> $GITHUB_OUTPUT
      - id: test
        run: just test_${{ matrix.compiler }} ${{ steps.args.outputs.args }}
      - id: test-valgrind
        if: matrix.compiler == 'clang'
        run: just test_valgrind ${{ steps.args.outputs.args }}
      - id: test-asan
        if: matrix.compiler == 'clang'
        run: just test_asan ${{ steps.args.outputs.args }}
      - id: test-msan
        if: matrix.compiler == 'clang'
        run: just test_msan ${{ steps.args.outputs.args }}
