name: test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [clang, gcc]
    steps:
      - uses: actions/checkout@v4
      - id: deps
        uses: mmalenic/evlist@main
      - id: test
        run: just test_${{ matrix.compiler }} -InputDeviceLister* ${{ steps.deps.outputs[format('{0}-version', matrix.compiler)] }}
      - id: test-valgrind
        if: matrix.compiler == 'clang'
        run: just test_valgrind -InputDeviceLister* ${{ steps.deps.outputs[format('{0}-version', matrix.compiler)] }}
      - id: test-asan
        if: matrix.compiler == 'clang'
        run: just test_asan -InputDeviceLister* ${{ steps.deps.outputs[format('{0}-version', matrix.compiler)] }}
      - id: test-msan
        if: matrix.compiler == 'clang'
        run: just test_msan -InputDeviceLister* ${{ steps.deps.outputs[format('{0}-version', matrix.compiler)] }}
